Integrate Lambda functions
Calligre/server pull request #10
Opened 2016-10-30 05:58 UTC by kyl191

Lambda has getting getting horrible over the need to pull in pre-built libs like cryptography and psycopg2, and was just an all-round hassle.

As part of the move, clean up the code as well.

2016-10-30 08:09 UTC, TheKevJames commented on api/__init__.py
> +import api.models.social
nitpick: alphabetize

2016-10-30 08:09 UTC, TheKevJames commented on api/__init__.py
> +                     '/social/get_upload_url')
not a very restful route

2016-10-30 08:09 UTC, TheKevJames commented on api/dynamo.py
> +import logging as log
Really gonna alias that for no reason? _sigh_ :P

2016-10-30 08:09 UTC, TheKevJames commented on api/dynamo.py
> +    if not hasattr(e, "response") or e.response.get("Error") is None:
Why `is None` over `not`?

2016-10-30 08:09 UTC, TheKevJames commented on api/dynamo.py
> +        return {"errors": [{"title": "Internal Error"}]}, \
Don't need `\` within dicts.

2016-10-30 08:09 UTC, TheKevJames commented on api/dynamo.py
> +    elif e.response.get("Error").get("Code") == \
Prefer fewer nested blocks when possible. If you already have a `return` in the above block, no need to `elif`/`else`.

2016-10-30 08:09 UTC, TheKevJames commented on api/dynamo.py
> +    r, status = get(params)
can we use better variable names than just `r`? `response`, maybe?

2016-10-30 08:09 UTC, TheKevJames commented on api/dynamo.py
> +        if status == 200:
Only 200?

2016-10-30 08:09 UTC, TheKevJames commented on api/models/social.py
> +                         "SELECT id, first_name, last_name FROM account \
use the same syntax for this as everywhere else, ie. triple quotes rather than `\`

2016-10-30 08:09 UTC, TheKevJames commented on api/models/social.py
> +        item["current_user_likes"] = (userid in item.get("likes", []))
no brackets

2016-10-30 08:09 UTC, TheKevJames commented on api/models/social.py
> +            "#ts,poster_id,#txt,media_link,like_count,likes",
This is hard to read (same alignment on keys and values). If you can't get linter to be happy, maybe assign the value to a variable and use that?

2016-10-30 08:09 UTC, TheKevJames commented on api/models/social.py
> +        if nextOffset is not None:
Why the `is not None`?

2016-10-30 08:09 UTC, TheKevJames commented on api/models/social.py
> +        # FIXME
If you are gonna merge FIXME's, make sure they have some info on 'em please.

2016-10-30 16:44 UTC, kyl191 commented on api/__init__.py
> +                     '/social/get_upload_url')
If you have a better idea... it's a single purpose endpoint.

2016-10-30 16:50 UTC, kyl191 commented on api/dynamo.py
> +import logging as log
`log.[error|warn|etc]` is so much cleaner.

2016-10-30 19:55 UTC, kyl191 commented on api/dynamo.py
> +        return {"errors": [{"title": "Internal Error"}]}, \
That's not part of a dict anymore...

2016-10-30 19:56 UTC, kyl191 commented on api/dynamo.py
> +        if status == 200:
Dynamo only responds with a 200: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Programming.Errors.html#Programming.Errors.Components

2016-11-01 01:49 UTC, TheKevJames commented on api/__init__.py
> +                     '/social/get_upload_url')
I think just make it `/image-upload-url`. No `get` since you're doing a `GET` already. `/social-image-upload-url` works, too, but I don't think that URL is specific to social content, just images. If it is social-related, I'd rather `social-image...` than` social/image...` since the latter collides with `/social/<postid>`.

2016-11-01 02:18 UTC, TheKevJames requested changes
Read through http://jsonapi.org/format/ , it's the format we're trying to stick to in responses, etc.

2016-11-01 02:18 UTC, TheKevJames commented on api/dynamo.py
> +        response = {"errors": [{"title": "Internal Error", "detail": status}]}
nitpick: all lowercase on `title` for consistency with the rest of the API

2016-11-01 02:18 UTC, TheKevJames commented on api/dynamo.py
> +        response = {"errors": [{"title": "Internal Error", "detail": status}]}
Use `'status': status` and set `'detail'` to something with more information. See http://jsonapi.org/format/#error-objects

2016-11-01 02:18 UTC, TheKevJames commented on api/dynamo.py
> +    log.error(e)
`logging.exception` whenever logging exceptions

2016-11-01 02:18 UTC, TheKevJames commented on api/dynamo.py
> +        return {"errors": [{"title": "Internal Error"}]}, \
Lowercase `'title'`, provide more info in response. See above.

2016-11-01 02:18 UTC, TheKevJames commented on api/dynamo.py
> +        return {"data": "No changes"}, \
`{'data': None}` for 304's

2016-11-01 02:18 UTC, TheKevJames commented on api/dynamo.py
> +        "title": e.response.get("Error", {}).get("Code"),
This should be `'status'`. Set `'title'` to a summary of the error (or something like "internal error" if none is available)

2016-11-01 02:18 UTC, TheKevJames commented on api/dynamo.py
> +            {"title": "The post you are trying to access doesn't exist."}]},\
Follow the same format as elsewhere (just "no record found"). Shouldn't be English, punctuated, etc, it's an error message.

2016-11-01 02:18 UTC, TheKevJames commented on api/dynamo.py
> +    return response.get("Items"), status
If Items is missing, does this work? I'm not sure if `return None, status` would be valid, we might want to default to `{}`.

2016-11-01 02:18 UTC, TheKevJames commented on api/dynamo.py
> +            return None, flask_api.status.HTTP_204_NO_CONTENT
`{'data': None}` instead of `None`.

2016-11-01 02:18 UTC, TheKevJames commented on api/models/social.py
> +    r, _ = database.gets("user",
You should check the error code here instead of ignoring it

2016-11-01 02:18 UTC, TheKevJames commented on api/models/social.py
> +    for row in r.get("data"):
`r.get('data', [])` in case the key is missing. Yes, I know that should not be the case.

2016-11-01 02:18 UTC, TheKevJames commented on api/models/social.py
> +        attrs = row.get("attributes")
`row.get("attributes", {})`

2016-11-01 02:18 UTC, TheKevJames commented on api/models/social.py
> +        mapping[attrs.get("id")] = " ".join((attrs.get("first_name"),
`attrs` not having an `id` field should be an error: use indexing instead of a `.get` to expose that, then handle that error.

2016-11-01 02:18 UTC, TheKevJames commented on api/models/social.py
> +                                             attrs.get("last_name")))
Default this and `first_name` to `''` rather than `None`, otherwise errors.

2016-11-01 02:18 UTC, TheKevJames commented on api/models/social.py
> +            Key("posts").eq("posts") & Key("timestamp").gt(Decimal(0)),
make this a variable please (or indent once if that fits PEP8), lining values up with keys is hard to read.

2016-11-01 02:18 UTC, TheKevJames commented on api/models/social.py
> +                "title": "You must provide either text or a media URL."}]}, \
See other error response comments

2016-11-01 02:18 UTC, TheKevJames commented on api/models/social.py
> +                               args.get("post_fb"),
Default this and `post_tw` to strings rather than `None` since you'll be casting to string in `external_post`. We want that to become `''`, not `'None'`

2016-11-01 02:18 UTC, TheKevJames commented on api/models/social.py
> +            log.error(e)
`log.exception` whenever you log exceptions

2016-11-01 02:18 UTC, TheKevJames commented on api/models/social.py
> +            Key("posts").eq("posts") & Key("timestamp").eq(Decimal(postid)),
See comment on indent or variable

2016-11-01 02:18 UTC, TheKevJames commented on api/models/social.py
> +                 "The post you are trying to delete isn't owned by you."}
see response comments

2016-11-01 02:18 UTC, TheKevJames commented on api/models/social.py
> +            Key("posts").eq("posts") & Key("timestamp").eq(postid),
indent/variable

2016-11-01 02:18 UTC, TheKevJames commented on api/models/social.py
> +            "DELETE likes :like SET like_count = like_count - :1",
indent/variable

2016-11-01 02:18 UTC, TheKevJames commented on api/models/social.py
> +            Key("posts").eq("posts") & Key("timestamp").eq(Decimal(postid)),
indent/variable

2016-11-01 02:18 UTC, TheKevJames commented on api/models/social.py
> +            "ADD likes :like SET like_count = like_count + :1",
indent/variable

2016-11-01 06:01 UTC, kyl191 commented on api/__init__.py
> +                     '/social/get_upload_url')
`/social-image-upload-api` it is.

2016-11-01 07:17 UTC, kyl191 commented on api/dynamo.py
> +        "title": e.response.get("Error", {}).get("Code"),
DynamoDB returns an error 'code' that is actually a string - eg `ConditionalCheckFailedException`

2016-11-01 07:18 UTC, kyl191 commented on api/dynamo.py
> +    return response.get("Items"), status
If we've gotten to this point, the response is a properly formatted dynamo response, which will have Items.

That said, adding a default works.

2016-11-02 01:35 UTC, TheKevJames commented on api/__init__.py
> +restful.add_resource(api.models.social.SingleSocialContent, '/social/<postid>')
Is `postid` numeric? `<int:postid>` would be nice if so.

2016-11-02 01:35 UTC, TheKevJames commented on api/dynamo.py
> +        "code": e.response.get("Error", {}).get("Code"),
`status`, not `code`

2016-11-02 08:05 UTC, TheKevJames approved these changes

2016-11-02 08:10 UTC, merged