Add support for (un)flagging posts + listing flagged posts
Calligre/server pull request #52
Opened 2017-03-19 20:21 UTC by kyl191

Resolves #50

2017-03-19 22:17 UTC, TheKevJames requested changes

2017-03-19 22:17 UTC, TheKevJames commented on api/models/social.py
> +flag_table = dynamo.DynamoWrapper(table_name='flagged')
May as well make this an env var as well

2017-03-19 22:17 UTC, TheKevJames commented on api/models/social.py
> +        item['like_count'] = str(item.get('like_count'), 0)
Pretty sure your brackets are wrong here. Don't you want: `str(item.get('like_count', 0))`?

2017-03-19 22:17 UTC, TheKevJames commented on api/models/social.py
> +        item['flag_count'] = str(item.get('flag_count'), 0)
Pretty sure your brackets are wrong here. Don't you want: `str(item.get('flag_count', 0))`?

2017-03-19 22:17 UTC, TheKevJames commented on api/models/social.py
> +        flag_table.put(params)
Do we need error/response handling here?

2017-03-20 03:09 UTC, kyl191 commented on api/models/social.py
> +        flag_table.put(params)
Both `patch` and `put` return a 204 on success. 

I've simplified it to just using the return value from the put.

2017-03-20 15:21 UTC, TheKevJames approved these changes

2017-03-20 23:29 UTC, merged